---

- hosts: webserver
  become: true
  tasks: 

  
  - name: install apache2 and php package for Ubuntu servers
    apt:
      name: 
        - apache2
        - libapache2-mod-php  
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


  - name: install apache2 and php package for CentOS server
    apt:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
