---

- hosts: webserver
  become: true
  tasks: 

  
  - name: install apache2 and php package for Ubuntu servers
    tags: always
    apt:
      name: 
        - apache2
        - libapache2-mod-php  
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


  - name: install apache2 and php package for CentOS server
    tags: always
    apt:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

- hosts: all
  become: true
  tasks:

  
  - name : add ssh for simone
    tags: always
    authorized_key: 
      user: simone
      key: ""
