---

- hosts: webserver
  become: true
  tasks:


  - name: install apache2 and php package for Ubuntu servers
    tags: always
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


- hosts: all
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.7.3/terraform_1.7.3_linux_386.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

  - name: install apache2 and php package for CentOS server
    tags: always
    apt:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

